import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {useStore} from "@nanostores/react";
import {authState} from "@/app/store/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Posts App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
